### ISSUE TITLE
Captura obrigatória + jogar novamente

### ISSUE THREAD

**Issue by EstherMart** [laisaluz/Draughts#5]
A peça que usamos para comer, não pode ser movimentada novamente no turno "quem come, joga dnv"

**Comment by EstherMart** [comment]
![Captura de tela 2023-06-21 213523](https://github.com/laisaluz/Draughts/assets/122387125/9578b6c2-8a52-4531-a41f-b9fd477428bc)

**Comment by EstherMart** [comment]
O PROBLEMA É QUEBRADO QUANDO ESSA PEÇA QUE COME, TEM, LOGO EM SEGUIDA, OUTRA PEÇA PARA COMER!!!!!!!!!!!!!!!!!!!!!!

**Comment by EstherMart** [comment]
![image](https://github.com/laisaluz/Draughts/assets/122387125/722af763-3f59-485c-8cc4-dcdf457e4584)

**Comment by EstherMart** [comment]
NÃO TA APARECEDNDO A MENSAGEM PERGUNATNDO QUAL PEÇA O ADVERSÁRIO QEUR COMER

**Comment by laisaluz** [comment]
- [ ] Printar a mensagem "Captura obrigatória"
- [ ] Testar
